'use client'
import React from 'react'
import Heading from '../ui/Heading/Heading'
import SubHeading from '../ui/SubHeading/SubHeading'
import Description from '../ui/Description/Description'
import Button from '../ui/Button/Button'
import Image from 'next/image'
import { planA ,productOneBgImage,blackbg } from '@/assets/images'

const PlanA = () => {

    const featuresData = [
        {
          title: "Total Managed Service",
          description:
            "Our Total Managed Plan is designed for Owners that don’t want to manage their charging network. This is a perfect option for Independent Property Owners.A portion of the estimated monthly revenue generated by the charging stations pays for Management and upgrades over a fixed term.",
          id: 2011,
        },
        {
          title: "Partner Managed Service",
          description:
            "Our Partner Plan gives Owners the opportunity to receive a larger percentage of the of the estimated monthly revenue while also benefiting from VoltiE’s Management Services.This Plan is great for Fleet Operators and mid-sized Property Owners. A smaller percentage of the revenue pays for Platform Management",
          id: 2012,
        },
        {
          title: "Operator Managed Service",
          description:
            "The Operator Managed Service gives a manager independent control over the entire EV Charging Platform. Larger Operators with multiple locations can leverage the total revenue potential from their EV Charging Network from day one.This Plan is designed for Hotels and Mall Operators who potentially have very large Networks.",
          id: 2013,
        },
        {
          title: "Custom Sevice Plans",
          description:
            "VoltiE creates Customized Service Plans for charge point operators. We consider several factors when we design our Partners EV Charging Network. Our technology integration and installation experience ensures that our Clients get the fastest most effective EV Network.",
          id: 2014,
        },
      ];
    return (
        // <section className='h-screen w-full relative'>
        //     <div className='w-full h-full bg-black flex items-center lg:gap-x-8 p-2 md:p-5 relative'>
        //         {/* Background Image */}
        //         <Image
        //             src={blackbg}
        //             alt='details-section-image-first'
        //             layout="fill"
        //             objectFit='cover'
        //             objectPosition='center'
        //         />
        //         {/* Content */}
        //         <div className='absolute inset-0 text-white gap-y-4 sm:gap-y-8 flex flex-col justify-center my-auto px-[5%]'>
        //             {/* <Heading name="Plan A" /> */}
        //             <SubHeading name="Total Managed Service" />
        //             <Description name='Our Total Managed Plan is designed for Owners that don’t want to manage their charging network. This is a perfect option for Independent Property Owners.A portion of the estimated monthly revenue generated by the charging stations pays for Management and upgrades over a fixed term.'/>
        //             <div className='flex justify-center md:justify-start items-center gap-2 md:gap-x-4 flex-wrap lg:flex-nowrap'>
        //                 <Button name="Contact us" bgColor='white' />
        //                 {/* <Button name="Learn More"  /> */}
        //             </div>
        //         </div>
        //     </div>
        // </section>

        <section className="relative h-full w-full overflow-hidden">
        <div className="h-[75vh] w-full mt-10">
          <Image
            src={blackbg}
            layout="fill"
            objectFit="cover"
            alt="slider-image-first"
          />
          <div className="absolute z-10 text-white w-full h-full   ">
            <div className=" p-12 flex-col gap-y-8 h-full">
              <div className=" mt-4 flex gap-y-10 w-full">
                {/* <Heading name="Why Choose Voltie ?" /> */}
              </div>
              <div className="w-[100%] mt-4 pt-12 flex flex-wrap gap-4   justify-center">
                {featuresData.map((slideData, index) => (
                  <div className="" key={slideData.id}>
                    <div
                      className="max-w-[300px]   min-h-[175px] shadow-lg rounded-lg  sm:p-6 overflow-h idden   gap-y-4 flex flex-col"
                   
                    >
                      <div className="flex gap-3 items-center justify-center mb-2">
                        {/* <span>✅</span> */}
                        {/* <div className=" text-center"> */}
                          <h2 className="mb-2 text-md text-center font-bold text-white">
                            {slideData.title}
                          </h2>
                        {/* </div> */}
                      </div>
                      <p className="mb-2 text-white   text-sm  text-center">
                        {slideData.description}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>
    );
}


export default PlanA