'use client'
import React from 'react'
import Heading from '../ui/Heading/Heading'
import SubHeading from '../ui/SubHeading/SubHeading'
import Description from '../ui/Description/Description'
import Button from '../ui/Button/Button'
import Image from 'next/image'
import { planA ,productOneBgImage,blackbg } from '@/assets/images'

const PlanA = () => {
    return (
        <section className='h-screen w-full relative'>
            <div className='w-full h-full bg-black flex items-center lg:gap-x-8 p-2 md:p-5 relative'>
                {/* Background Image */}
                <Image
                    src={blackbg}
                    alt='details-section-image-first'
                    layout="fill"
                    objectFit='cover'
                    objectPosition='center'
                />
                {/* Content */}
                <div className='absolute inset-0 text-white gap-y-4 sm:gap-y-8 flex flex-col justify-center my-auto px-[5%]'>
                    {/* <Heading name="Plan A" /> */}
                    <SubHeading name="Total Managed Service" />
                    <Description name='Our Total Managed Plan is designed for Owners that don’t want to manage their charging network. This is a perfect option for Independent Property Owners.A portion of the estimated monthly revenue generated by the charging stations pays for Management and upgrades over a fixed term.'/>
                    <div className='flex justify-center md:justify-start items-center gap-2 md:gap-x-4 flex-wrap lg:flex-nowrap'>
                        <Button name="Contact us" bgColor='white' />
                        {/* <Button name="Learn More"  /> */}
                    </div>
                </div>
            </div>
        </section>
    );
}


export default PlanA